name: Test and Lint

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test-and-lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt
          pip install black flake8

      - name: Run tests
        run: |
          source venv/bin/activate
          pytest

      - name: Run Flake8
        run: |
          source venv/bin/activate
          flake8 .

      - name: Run Black
        run: |
          source venv/bin/activate
          black --check .
